params = {
    -1: dict(n_dims=128, combining_factor=0.1,
            collaborative_params=dict(
                prediction_network_params=dict(lr=0.05, epochs=50, batch_size=1536,
                                               network_depth=3,
                                               gaussian_noise=0.1, conv_depth=3,
                                               kernel_l2=1e-9, dropout=0.0, ),
                user_item_params=dict(gcn_lr=0.0005, gcn_epochs=10, gcn_layers=3, gcn_dropout=0.0,
                                      gcn_kernel_l2=1e-8, gcn_batch_size=1024, conv_depth=3,
                                      margin=1.0,
                                      gaussian_noise=0.05,
                                      node2vec_params=dict(num_walks=150, q=0.5)))),
    0: dict(n_dims=128, combining_factor=0.1,
            collaborative_params=dict(
                prediction_network_params=dict(lr=0.05, epochs=50, batch_size=1536,
                                               network_depth=3,
                                               gaussian_noise=0.1, conv_depth=3,
                                               kernel_l2=1e-9, dropout=0.0, ),
                user_item_params=dict(gcn_lr=0.0005, gcn_epochs=10, gcn_layers=3, gcn_dropout=0.0,
                                      gcn_kernel_l2=1e-8, gcn_batch_size=1024, conv_depth=3,
                                      margin=1.0,
                                      gaussian_noise=0.05,
                                      node2vec_params=dict(num_walks=150, q=0.5)))),
    2: dict(n_dims=112, combining_factor=0.1,
            collaborative_params=dict(
                prediction_network_params=dict(lr=0.05, epochs=15, batch_size=1536,
                                               network_depth=3,
                                               gaussian_noise=0.01, conv_depth=2,
                                               kernel_l2=1e-9, ),
                user_item_params=dict(gcn_lr=0.00025, gcn_epochs=10, gcn_layers=1,
                                      gcn_kernel_l2=1e-6, gcn_batch_size=1024, conv_depth=2,
                                      margin=1.0,
                                      gaussian_noise=0.1,
                                      node2vec_params=dict(num_walks=50, q=0.5)))),
    3: dict(n_dims=112, combining_factor=0.1,
            collaborative_params=dict(
                prediction_network_params=dict(lr=0.05, epochs=100, batch_size=1536,
                                               network_depth=3,
                                               gaussian_noise=0.35, conv_depth=2,
                                               kernel_l2=1e-9, dropout=0.0, ),
                user_item_params=dict(gcn_lr=0.00075, gcn_epochs=20, gcn_layers=2, gcn_dropout=0.0,
                                      gcn_kernel_l2=1e-8, gcn_batch_size=1024,
                                      margin=1.0,
                                      gaussian_noise=0.15,
                                      node2vec_params=dict(num_walks=150, q=0.25)))),
    4: dict(n_dims=112, combining_factor=0.1,
            collaborative_params=dict(
                prediction_network_params=dict(lr=0.05, epochs=100, batch_size=1536,
                                               network_depth=3,
                                               gaussian_noise=0.35, conv_depth=2,
                                               kernel_l2=1e-9, dropout=0.0, ),
                user_item_params=dict(gcn_lr=0.00025, gcn_epochs=10, gcn_layers=2, gcn_dropout=0.0,
                                      gcn_kernel_l2=1e-8, gcn_batch_size=1024, conv_depth=2,
                                      margin=1.0,
                                      gaussian_noise=0.05,
                                      node2vec_params=dict(num_walks=150, q=0.25)))),
}
